import './globals.css'
import type { Metadata } from 'next'



export const metadata: Metadata = {
  title: 'Sublime Data Systems',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-roboto">{children}</body>
    </html>
  )
}
